from os import environ
import urllib

from rest_framework.exceptions import ParseError, PermissionDenied
from rest_framework.response import Response
from rest_framework.views import APIView


GATHERER_URI = 'http://gatherer.wizards.com/Handlers/Image.ashx?type=card'
ALIASES = {
    'bob':  'Dark Confidant',
    'bear':  'Grizzly Bears',
    'bears':  'Grizzly Bears',
    'crow':  'Storm Crow'
}
SET_ALIASES = {
    u'all': u'al',
    u'pgpx': u'pgpx',
    u'ptk': u'pk',
    u'duel decks: elspeth vs. kiora': u'ddo',
    u'scg': u'scg',
    u'roe': u'roe',
    u'ala': u'ala',
    u'mirage': u'mi',
    u'planechase 2012 edition': u'pc2',
    u'darksteel': u'dst',
    u'v12': u'v12',
    u'v13': u'v13',
    u'release events': u'prel',
    u'te': u'te',
    u'cm1': u'cm1',
    u'magic origins': u'ori',
    u'v11': u'v11',
    u'duel decks: jace vs. vraska': u'ddm',
    u'4ed': u'4e',
    u'lrw': u'lrw',
    u'v15': u'v15',
    u'cmd': u'cmd',
    u'masters edition ii': u'me2',
    u'limited edition beta': u'2e',
    u'evg': u'evg',
    u'masters edition iv': u'me4',
    u'dis': u'dis',
    u'ody': u'od',
    u'10e': u'10e',
    u'me4': u'me4',
    u'me3': u'me3',
    u'me2': u'me2',
    u"urza's legacy":u'gu',
    u'tempest': u'te',
    u'time spiral': u'tsp',
    u'judge gift program': u'pjgp',
    u'3e': u'3e',
    u'duel decks: heroes vs. monsters': u'ddl',
    u'med': u'med',
    u'leb': u'2e',
    u'magic: the gathering-commander': u'cmd',
    u'leg': u'le',
    u'rise of the eldrazi': u'roe',
    u'mirrodin': u'mrd',
    u'celebration': u'pcel',
    u'p15a': u'p15a',
    u'drk': u'dk',
    u'bok': u'bok',
    u'dgm': u'dgm',
    u'pwor': u'pwor',
    u'pwos': u'pwos',
    u'drb': u'drb',
    u's00': u'p4',
    u'friday night magic': u'pfnm',
    u'vis': u'vi',
    u'magic 2014 core set': u'm14',
    u'alara reborn': u'arb',
    u'apc': u'ap',
    u'brb': u'br',
    u'champs and states': u'pcmp',
    u'usg': u'uz',
    u'prel': u'prel',
    u'pmpr': u'pmpr',
    u'fem': u'fe',
    u'tempest remastered': u'tpr',
    u'chr': u'ch',
    u'p2hg': u'p2hg',
    u'duel decks anthology',
    u'elves vs. goblins': u'dd3_evg',
    u'champions of kamigawa': u'chk',
    u'world magic cup qualifiers': u'pwcq',
    u'3ed': u'3e',
    u'phho': u'phho',
    u'prophecy': u'pr',
    u'pwpn': u'pwpn',
    u'betrayers of kamigawa': u'bok',
    u'mm': u'mm',
    u"ugin's fate promos":u'frf_ugin',
    u'mi': u'mi',
    u'duels of the planeswalkers': u'dpa',
    u'prerelease events': u'ppre',
    u'ulg': u'gu',
    u'onslaught': u'ons',
    u'the dark': u'dk',
    u'duel decks: divine vs. demonic': u'ddc',
    u'from the vault: annihilation (2014)': u'v14',
    u'dd3_jvc': u'dd3_jvc',
    u'duel decks: elves vs. goblins': u'evg',
    u'guru': u'pgru',
    u'gatecrash': u'gtc',
    u'hop': u'hop',
    u'cst': u'cst',
    u'csp': u'csp',
    u'nph': u'nph',
    u'seventh edition': u'7e',
    u'clash pack': u'cpk',
    u'v09': u'v09',
    u'conflux': u'con',
    u'zendikar': u'zen',
    u'fe': u'fe',
    u'invasion': u'in',
    u'stronghold': u'st',
    u'saviors of kamigawa': u'sok',
    u'scourge': u'scg',
    u'super series': u'psus',
    u'modern masters': u'mma',
    u'st': u'st',
    u'eventide': u'eve',
    u'unglued': u'ug',
    u'zen': u'zen',
    u'vma': u'vma',
    u'two-headed giant tournament': u'p2hg',
    u'itp': u'itp',
    u'pcy': u'pr',
    u'morningtide': u'mor',
    u'tsb': u'tsb',
    u'eighth edition': u'8ed',
    u'tsp': u'tsp',
    u'ced': u'ced',
    u'cei': u'cei',
    u"dragon's maze":u'dgm',
    u'pmei': u'pmei',
    u'worlds': u'pwor',
    u'psus': u'psus',
    u'pc2': u'pc2',
    u'2e': u'2e',
    u'from the vault: realms': u'v12',
    u'psum': u'psum',
    u'legions': u'lgn',
    u'media inserts': u'pmei',
    u'mm2': u'mm2',
    u'ex': u'ex',
    u'shards of alara': u'ala',
    u'dst': u'dst',
    u'dd3_dvd': u'dd3_dvd',
    u'limited edition alpha': u'1e',
    u"urza's saga":u'uz',
    u'exodus': u'ex',
    u"collector's edition":u'ced',
    u'mmq': u'mm',
    u'9ed': u'9ed',
    u'ori': u'ori',
    u'premium deck series: graveborn': u'pd3',
    u'md1': u'md1',
    u'mma': u'mma',
    u'battle for zendikar': u'bfz',
    u'7ed': u'7e',
    u'ath': u'ath',
    u'duel decks: ajani vs. nicol bolas': u'ddh',
    u'atq': u'aq',
    u'apocalypse': u'ap',
    u'isd': u'isd',
    u'duel decks: elspeth vs. tezzeret': u'ddf',
    u'ons': u'ons',
    u'visions': u'vi',
    u'tor': u'tor',
    u'pcel': u'pcel',
    u'duel decks anthology',
    u'jace vs. chandra': u'dd3_jvc',
    u'1e': u'1e',
    u'fallen empires': u'fe',
    u'gpt': u'gpt',
    u'wizards of the coast online store': u'pwos',
    u'uds': u'cg',
    u'parl': u'parl',
    u'duel decks:  sorin vs. tibalt': u'ddk',
    u'mercadian masques': u'mm',
    u'legend membership': u'plgm',
    u'dtk': u'dtk',
    u'sth': u'st',
    u'pjgp': u'pjgp',
    u'gtc': u'gtc',
    u'ktk': u'ktk',
    u'magic player rewards': u'pmpr',
    u'7e': u'7e',
    u'ninth edition': u'9ed',
    u'fourth edition': u'4e',
    u'scars of mirrodin': u'som',
    u'rav': u'rav',
    u'torment': u'tor',
    u'premium deck series:  fire and lightning': u'pd2',
    u'portal second age': u'p2',
    u'new phyrexia': u'nph',
    u'anthologies': u'ath',
    u'chronicles': u'ch',
    u'mir': u'mi',
    u'dd3_evg': u'dd3_evg',
    u'from the vault:  legends': u'v11',
    u'journey into nyx': u'jou',
    u'arena league': u'parl',
    u'pcmp': u'pcmp',
    u'exo': u'ex',
    u'worldwake': u'wwk',
    u'exp': u'exp',
    u'european land program': u'pelp',
    u'mrd': u'mrd',
    u'from the vault: angels': u'v15',
    u'ugl': u'ug',
    u'frf_ugin': u'frf_ugin',
    u'pd3': u'pd3',
    u'v10': u'v10',
    u'hm': u'hm',
    u'v14': u'v14',
    u'magic 2011': u'm11',
    u'rtr': u'rtr',
    u'nemesis': u'ne',
    u'masters edition': u'med',
    u'ice age': u'ia',
    u'bfz': u'bfz',
    u'mgb': u'mgb',
    u'dk': u'dk',
    u'cg': u'cg',
    u'duel decks: zendikar vs. eldrazi': u'ddp',
    u'avacyn restored': u'avr',
    u'lorwyn': u'lrw',
    u'dpa': u'dpa',
    u'shm': u'shm',
    u'duel decks anthology',
    u'garruk vs. liliana': u'dd3_gvl',
    u'battle royale box set': u'br',
    u'lea': u'1e',
    u'from the vault: twenty': u'v13',
    u'btd': u'bd',
    u'arb': u'arb',
    u'arc': u'arc',
    u'arn': u'an',
    u'from the vault: relics': u'v10',
    u'rivals quick start set': u'rqs',
    u'magic 2010': u'm10',
    u'pd2': u'pd2',
    u'magic 2012': u'm12',
    u'magic 2013': u'm13',
    u'starter 1999': u'p3',
    u'mirrodin besieged': u'mbs',
    u'jou': u'jou',
    u'wl': u'wl',
    u'le': u'le',
    u'wth': u'wl',
    u's99': u'p3',
    u'duel decks anthology',
    u'divine vs. demonic': u'dd3_dvd',
    u'duel decks: speed vs. cunning': u'ddn',
    u'dka': u'dka',
    u'unh': u'unh',
    u'dkm': u'dkm',
    u'con': u'con',
    u'ch': u'ch',
    u'por': u'po',
    u'm11': u'm11',
    u'm10': u'm10',
    u'm13': u'm13',
    u'm12': u'm12',
    u'm15': u'm15',
    u'm14': u'm14',
    u'international collector\'s edition': u'cei',
    u'pr': u'pr',
    u'ps': u'ps',
    u'frf': u'frf',
    u'plpa': u'plpa',
    u'planeshift': u'ps',
    u'pk': u'pk',
    u'po': u'po',
    u'lgn': u'lgn',
    u'6e': u'6e',
    u'5ed': u'5e',
    u'po2': u'p2',
    u"commander's arsenal":u'cm1',
    u'dissension': u'dis',
    u'hml': u'hm',
    u'return to ravnica': u'rtr',
    u'odyssey': u'od',
    u'p2': u'p2',
    u'p3': u'p3',
    u'fut': u'fut',
    u'coldsnap theme decks': u'cst',
    u'p4': u'p4',
    u'portal demo game': u'ppod',
    u'pgru': u'pgru',
    u'asia pacific land program': u'palp',
    u'vi': u'vi',
    u'avr': u'avr',
    u'eve': u'eve',
    u'unlimited edition': u'2u',
    u'happy holidays': u'phho',
    u'commander 2015': u'c15',
    u'commander 2014': u'c14',
    u'in': u'in',
    u'ia': u'ia',
    u'alliances': u'al',
    u'starter 2000': u'p4',
    u'duel decks: jace vs. chandra': u'dd2',
    u'ddn': u'ddn',
    u'deckmasters': u'dkm',
    u'guildpact': u'gpt',
    u'8ed': u'8ed',
    u'planechase': u'hop',
    u'5e': u'5e',
    u'fate reforged': u'frf',
    u'pmgd': u'pmgd',
    u'portal': u'po',
    u'fifth dawn': u'5dn',
    u'ppre': u'ppre',
    u'judgment': u'jud',
    u'ppro': u'ppro',
    u'coldsnap': u'csp',
    u'ths': u'ths',
    u'from the vault: dragons': u'drb',
    u'fifth edition': u'5e',
    u"urza's destiny":u'cg',
    u'gu': u'gu',
    u'duel decks: knights vs. dragons': u'ddg',
    u'theros': u'ths',
    u'dragons of tarkir': u'dtk',
    u'pdrc': u'pdrc',
    u'multiverse gift box': u'mgb',
    u'c13': u'c13',
    u'bng': u'bng',
    u'c15': u'c15',
    u'c14': u'c14',
    u'homelands': u'hm',
    u'2u': u'2u',
    u'mor': u'mor',
    u'time spiral "timeshifted"': u'tsb',
    u'vintage masters': u'vma',
    u'innistrad': u'isd',
    u'born of the gods': u'bng',
    u'duel decks: izzet vs. golgari': u'ddj',
    u'premium deck series: slivers': u'h09',
    u'palp': u'palp',
    u'pfnm': u'pfnm',
    u'archenemy': u'arc',
    u'modern event deck 2014': u'md1',
    u'future sight': u'fut',
    u'rqs': u'rqs',
    u'tmp': u'te',
    u'cns': u'cns',
    u'ddp': u'ddp',
    u'pelp': u'pelp',
    u'ice': u'ia',
    u'gateway': u'pgtw',
    u'ddk': u'ddk',
    u'ddj': u'ddj',
    u'ddi': u'ddi',
    u'ddh': u'ddh',
    u'ddo': u'ddo',
    u'revised edition': u'3e',
    u'ddm': u'ddm',
    u'ddl': u'ddl',
    u'ddc': u'ddc',
    u'ddg': u'ddg',
    u'ddf': u'ddf',
    u'dde': u'dde',
    u'ddd': u'ddd',
    u'bd': u'bd',
    u'khans of tarkir': u'ktk',
    u'duel decks: garruk vs. liliana': u'ddd',
    u'pls': u'ps',
    u'nms': u'ne',
    u'dragon con': u'pdrc',
    u'beatdown box set': u'bd',
    u'plc': u'plc',
    u'br': u'br',
    u'unhinged': u'unh',
    u'dd2': u'dd2',
    u'od': u'od',
    u'2ed': u'2u',
    u'duel decks: phyrexia vs. the coalition': u'dde',
    u'pgtw': u'pgtw',
    u'chk': u'chk',
    u'ravnica: city of guilds': u'rav',
    u'sok': u'sok',
    u'som': u'som',
    u'classic sixth edition': u'6e',
    u'modern masters 2015 edition': u'mm2',
    u'tenth edition': u'10e',
    u'summer of magic': u'psum',
    u'5dn': u'5dn',
    u'mbs': u'mbs',
    u'h09': u'h09',
    u'van': u'van',
    u'legends': u'le',
    u'introductory two-player set': u'itp',
    u'magic game day': u'pmgd',
    u'jud': u'jud',
    u'masters edition iii': u'me3',
    u'ppod': u'ppod',
    u'plgm': u'plgm',
    u'shadowmoor': u'shm',
    u'launch parties': u'plpa',
    u'uz': u'uz',
    u'dark ascension': u'dka',
    u'vanguard': u'van',
    u'ug': u'ug',
    u'commander 2013 edition': u'c13',
    u'15th anniversary': u'p15a',
    u'inv': u'in',
    u'wizards play network': u'pwpn',
    u'al': u'al',
    u'an': u'an',
    u'aq': u'aq',
    u'ap': u'ap',
    u'planar chaos': u'plc',
    u'grand prix': u'pgpx',
    u'magic 2015 core set': u'm15',
    u'portal three kingdoms': u'pk',
    u'ne': u'ne',
    u'wwk': u'wwk',
    u'arabian nights': u'an',
    u'magic: the gathering conspiracy': u'cns',
    u'tpr': u'tpr',
    u'pro tour': u'ppro',
    u'from the vault: exiled': u'v09',
    u'antiquities': u'aq',
    u'cpk': u'cpk',
    u'dd3_gvl': u'dd3_gvl',
    u'zendikar expeditions': u'exp',
    u'duel decks: venser vs. koth': u'ddi',
    u'6ed': u'6e',
    u'pwcq': u'pwcq',
    u'4e': u'4e',
    u'weatherlight': u'wl'
}


class RootView(APIView):
    """
    Nothing here but me.
    """
    def get(self, request):
        return Response({'root':  'Psst, go to the /magicslack/ endpoint.'})


class SlackMagicCardView(APIView):
    """
    Slack webhook interface for returning details of magic card.
    """
    def post(self, request):
        if 'token' not in request.data:
            raise PermissionDenied
        if request.data['token'] != environ['SLACK_HOOK_TOKEN'] and request.data['token'] != environ['SLACK_SLASH_TOKEN']:
            raise PermissionDenied

        if 'text' not in request.data:
            raise ParseError

        command = request.data['text']
        # Get set name first
        set_code = ''
        if '\\\\' in command:
            csplit = command.split('\\\\')
            set_name = csplit[1].strip(' ').lower()
            set_code = SET_ALIASES.get(set_name, '')
            command = csplit[0]

        if command.startswith('magicbot:'):
            card_name = command.encode('utf-8')[9:].strip(' ')
        else:
            card_name = command.encode('utf-8').strip(' ')

        # Catch Slack's garbage /u2019 in the name of Manor Skeleton
        try:
            card_name = card_name.decode('utf-8').replace(u'\u2019', u'\'')
        except Exception as e:
            print e
        try:
            card_name = str(card_name)
        except UnicodeDecodeError:
            card_name = 'manor skeleton'
        except Exception as e:
            print e

        if card_name.lower() in ALIASES:
            card_name = ALIASES[card_name.lower()]

        card_img_uri = '{}&name={}&set={}'.format(
            GATHERER_URI, urllib.quote_plus(card_name), set_code)

        return Response({
            'text':  card_img_uri
        })
